apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portal-arquitectura
  title: Portal de Arquitectura
  description: Documentación técnica y recursos del equipo de Arquitectura
  tags:
    - arquitectura
    - documentacion
  annotations:
    backstage.io/techdocs-ref: dir:./docs
spec:
  type: documentation
  lifecycle: production
  owner: arquitectura
